# Generated by Django 5.0.5 on 2026-02-23 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bou', models.CharField(max_length=50, unique=True)),
                ('vara', models.CharField(choices=[('VARA_01', '1ª Vara Criminal'), ('VARA_02', '2ª Vara Criminal'), ('VARA_03', '3ª Vara Criminal')], max_length=20)),
                ('processo', models.CharField(max_length=50)),
                ('policial_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('policial_graduacao', models.CharField(blank=True, choices=[('SD', 'Soldado'), ('CB', 'Cabo'), ('3SGT', '3º Sargento'), ('2SGT', '2º Sargento'), ('1SGT', '1º Sargento'), ('SUB', 'Subtenente'), ('TEN', 'Tenente'), ('CAP', 'Capitão')], max_length=10, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteIncineracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Código do Lote')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_incineracao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ABERTO', max_length=20)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('substancia', models.CharField(choices=[('MACONHA', 'Maconha'), ('COCAINA', 'Cocaína'), ('CRACK', 'Crack'), ('PE_MACONHA', 'Pé de Maconha'), ('SINTETICA', 'Droga Sintética'), ('ECSTASY', 'Ecstasy'), ('SKUNK', 'Skunk'), ('HAXIXE', 'Haxixe'), ('OUTROS', 'Outros')], max_length=50)),
                ('outra_substancia', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_estimado', models.FloatField()),
                ('peso_real', models.FloatField(blank=True, null=True)),
                ('unidade', models.CharField(choices=[('G', 'Gramas (g)'), ('U', 'Unidades (un)')], default='G', max_length=2)),
                ('numero_vestigio', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('caixa', models.CharField(blank=True, max_length=10, null=True)),
                ('n_oficio', models.CharField(blank=True, max_length=50, null=True)),
                ('data_incineracao', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='gestao.loteincineracao')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to=settings.AUTH_USER_MODEL)),
                ('noticiado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='gestao.noticiado')),
            ],
        ),
        migrations.AddField(
            model_name='noticiado',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticiados', to='gestao.ocorrencia'),
        ),
        migrations.CreateModel(
            name='RegistroHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('status_novo', models.CharField(max_length=20)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='gestao.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
