# Generated by Django 6.0.2 on 2026-02-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bou', models.CharField(max_length=50, unique=True, verbose_name='BOU')),
                ('substancia', models.CharField(max_length=100, verbose_name='Substância')),
                ('peso_estimado', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso Estimado (g)')),
                ('peso_real', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Real (g)')),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
