# Generated by Django 5.0.5 on 2026-04-02 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteIncineracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Código do Lote')),
                ('data_incineracao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('INCINERADO', 'Incinerado')], default='ABERTO', max_length=20)),
                ('eprotocolo_geral', models.CharField(blank=True, max_length=50, null=True, verbose_name='eProtocolo do Comando')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Incineração',
                'verbose_name_plural': 'Lotes de Incineração',
            },
        ),
        migrations.CreateModel(
            name='Noticiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('ENTORPECENTE', 'Entorpecente'), ('SOM', 'Equipamento de Som (Perturbação)'), ('FACA', 'Arma Branca / Faca'), ('SIMULACRO', 'Simulacro / Arma de Fogo'), ('OUTROS', 'Outros Objetos (Gerais)'), ('DINHEIRO', 'Dinheiro / Valores monetários')], default='ENTORPECENTE', max_length=50)),
                ('substancia', models.CharField(blank=True, choices=[('MACONHA', 'Maconha'), ('COCAINA', 'Cocaína'), ('CRACK', 'Crack'), ('PE_MACONHA', 'Pé de Maconha'), ('SINTETICA', 'Droga Sintética'), ('ECSTASY', 'Ecstasy'), ('SKUNK', 'Skunk'), ('HAXIXE', 'Haxixe'), ('OUTROS', 'Outros')], max_length=50, null=True)),
                ('outra_substancia', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_estimado', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso Estimado')),
                ('peso_real', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso Real')),
                ('unidade', models.CharField(blank=True, choices=[('G', 'Gramas (g)'), ('KG', 'Quilos (kg)'), ('UN', 'Unidades (Pés/Comprimidos)')], max_length=3, null=True)),
                ('descricao_geral', models.TextField(blank=True, help_text='Ex: Marca do som, modelo do simulacro, etc.', null=True)),
                ('valor_monetario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor em Dinheiro (R$)')),
                ('recibo_forum', models.FileField(blank=True, null=True, upload_to='recibos/forum/', verbose_name='Recibo Assinado do Fórum')),
                ('comprovante_deposito', models.FileField(blank=True, null=True, upload_to='recibos/deposito/', verbose_name='Comprovante de Depósito PIX/TED')),
                ('numero_lacre', models.CharField(max_length=50, verbose_name='Nº Lacre (Cadeia de Custódia)')),
                ('localizacao_no_cofre', models.CharField(blank=True, help_text='Ex: Armário 1, Prateleira B', max_length=100, null=True)),
                ('status', models.CharField(choices=[('RECEBIDO', 'Entrada no Cartório (Lacre Conferido)'), ('CONSTATAÇÃO', 'Processamento (Auto de Constatação Realizado)'), ('ARMAZENADO', 'Armazenamento (No Cofre)'), ('RETIRADO_PERICIA', 'Saída Temporária (Enviado para Perícia Externa)'), ('RETORNO_PERICIA', 'Retorno de Perícia (Re-armazenado)'), ('AUTORIZADO', 'Aguardando Incineração (Ordem Judicial)'), ('TRANSPORTE', 'Em Transporte (Para Destruição)'), ('INCINERADO', 'Fim de Custódia (Incinerado)'), ('AGUARDANDO_OFICIO', 'Aguardando Geração de Ofício (Materiais Gerais)'), ('OFICIO_GERADO', 'Ofício Gerado (Aguardando Transporte)'), ('EM_TRANSPORTE_FORUM', 'Em Transporte (Para o Fórum)'), ('ENTREGUE_AO_JUDICIARIO', 'Entregue ao Judiciário (Fórum / Recibo Anexado)'), ('AGUARDANDO_GUIA', 'Aguardando Guia de Depósito (Dinheiro)'), ('GUIA_GERADA', 'Guia Gerada (Aguardando Depósito)'), ('DEPOSITADO_JUDICIALMENTE', 'Depositado (Comprovante Anexado)')], default='RECEBIDO', max_length=50)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='gestao.loteincineracao')),
                ('noticiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='gestao.noticiado')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('bou', models.CharField(max_length=20, unique=True, verbose_name='BOU')),
                ('vara', models.CharField(choices=[('VARA_01', '1ª Vara Criminal'), ('VARA_02', '2ª Vara Criminal'), ('VARA_03', '3ª Vara Criminal')], max_length=20)),
                ('processo', models.CharField(blank=True, max_length=30, null=True, verbose_name='PROJUDI')),
                ('policial_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('policial_graduacao', models.CharField(blank=True, choices=[('SD', 'Soldado'), ('CB', 'Cabo'), ('3SGT', '3º Sargento'), ('2SGT', '2º Sargento'), ('1SGT', '1º Sargento'), ('SUB', 'Subtenente'), ('2TEN', '2º Tenente'), ('1TEN', '1º Tenente'), ('CAP', 'Capitão'), ('MAJ', 'Major')], max_length=10, null=True)),
                ('rg_policial', models.CharField(blank=True, max_length=20, null=True)),
                ('unidade_origem', models.CharField(choices=[('RPA', 'RPA'), ('DEAEV', 'DEAEV'), ('ROCAM', 'ROCAM'), ('GOTRAN', 'GOTRAN'), ('CAVALARIA', 'CAVALARIA'), ('CHOQUE', 'CHOQUE'), ('CHOQUE CANIL', 'CHOQUE CANIL'), ('TRANSITO', 'TRANSITO'), ('ROTAM', 'ROTAM'), ('CPU', 'CPU'), ('P2', 'P2'), ('OUTRA', 'Outra Unidade (Especificar)')], default='RPA', max_length=20)),
                ('unidade_especifica', models.CharField(blank=True, max_length=100, null=True)),
                ('data_registro_bou', models.DateField(blank=True, null=True, verbose_name='Data do Fato (BOU)')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='noticiado',
            name='ocorrencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticiados', to='gestao.ocorrencia'),
        ),
        migrations.CreateModel(
            name='RegistroHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('status_na_epoca', models.CharField(choices=[('RECEBIDO', 'Entrada no Cartório (Lacre Conferido)'), ('CONSTATAÇÃO', 'Processamento (Auto de Constatação Realizado)'), ('ARMAZENADO', 'Armazenamento (No Cofre)'), ('RETIRADO_PERICIA', 'Saída Temporária (Enviado para Perícia Externa)'), ('RETORNO_PERICIA', 'Retorno de Perícia (Re-armazenado)'), ('AUTORIZADO', 'Aguardando Incineração (Ordem Judicial)'), ('TRANSPORTE', 'Em Transporte (Para Destruição)'), ('INCINERADO', 'Fim de Custódia (Incinerado)'), ('AGUARDANDO_OFICIO', 'Aguardando Geração de Ofício (Materiais Gerais)'), ('OFICIO_GERADO', 'Ofício Gerado (Aguardando Transporte)'), ('EM_TRANSPORTE_FORUM', 'Em Transporte (Para o Fórum)'), ('ENTREGUE_AO_JUDICIARIO', 'Entregue ao Judiciário (Fórum / Recibo Anexado)'), ('AGUARDANDO_GUIA', 'Aguardando Guia de Depósito (Dinheiro)'), ('GUIA_GERADA', 'Guia Gerada (Aguardando Depósito)'), ('DEPOSITADO_JUDICIALMENTE', 'Depositado (Comprovante Anexado)')], max_length=50)),
                ('observacao', models.TextField(blank=True, help_text="Descreva: 'Droga guardada no cofre', 'Retirada para pesagem real', etc.", null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='gestao.material')),
            ],
            options={
                'verbose_name': 'Registro de Movimentação',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
