# Generated by Django 5.0.5 on 2026-02-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='posicao_sacola',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificação da Sacola/Sublote'),
        ),
    ]
