# Generated by Django 6.0.2 on 2026-02-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='caixa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caixa/Localização'),
        ),
        migrations.AddField(
            model_name='material',
            name='n_oficio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Ofício Incineração'),
        ),
        migrations.AddField(
            model_name='material',
            name='noticiado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Noticiado/Réu'),
        ),
        migrations.AddField(
            model_name='material',
            name='vara',
            field=models.CharField(choices=[('1ª VARA', '1ª Vara Criminal'), ('2ª VARA', '2ª Vara Criminal'), ('3ª VARA', '3ª Vara Criminal')], default='1ª VARA', max_length=20, verbose_name='Vara Criminal'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Conferência'), ('NO_COFRE', 'No Cofre'), ('INCINERADO', 'Incinerado')], default='PENDENTE', max_length=20),
        ),
    ]
