# Generated by Django 6.0.3 on 2026-04-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nome_popular',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Popular / Característica'),
        ),
        migrations.AddField(
            model_name='material',
            name='uso_pessoal',
            field=models.BooleanField(default=False, verbose_name='Uso Pessoal?'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='natureza_penal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipos Penais / Natureza'),
        ),
    ]
