# Generated by Django 5.0.5 on 2026-03-18 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteincineracao',
            options={'verbose_name': 'Lote de Incineração', 'verbose_name_plural': 'Lotes de Incineração'},
        ),
        migrations.AddField(
            model_name='material',
            name='numero_lacre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Lacre/Vestígio'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='unidade_especifica',
            field=models.CharField(blank=True, help_text='Caso seja unidade de fora', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='unidade_origem',
            field=models.CharField(choices=[('1CIA', '1ª CIA'), ('2CIA', '2ª CIA'), ('ROCAM', 'ROCAM'), ('CHOQUE', 'CHOQUE'), ('OUTRA', 'Outra Unidade (Especificar)')], default='1CIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='noticiado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='gestao.noticiado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Conferência'), ('NO_COFRE', 'No Cofre'), ('AUTORIZADO', 'Pronto para Queima'), ('INCINERADO', 'Incinerado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='policial_graduacao',
            field=models.CharField(blank=True, choices=[('SD', 'Soldado'), ('CB', 'Cabo'), ('3SGT', '3º Sargento'), ('2SGT', '2º Sargento'), ('1SGT', '1º Sargento'), ('SUB', 'Subtenente'), ('2TEN', '2º Tenente'), ('1TEN', '1º Tenente'), ('CAP', 'Capitão'), ('MAJ', 'Major')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='processo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='PROJUDI'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='vara',
            field=models.CharField(choices=[('VARA_01', '1ª Vara Criminal'), ('VARA_02', '2ª Vara Criminal'), ('VARA_03', '3ª Vara Criminal'), ('JECRIM', 'Juizado Especial (JECRIM)')], max_length=20),
        ),
    ]
