# Generated by Django 5.0.5 on 2026-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_material_caixa_material_n_oficio_material_noticiado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='data_incineracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Queima'),
        ),
        migrations.AddField(
            model_name='material',
            name='data_oficio',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Ofício'),
        ),
        migrations.AlterField(
            model_name='material',
            name='caixa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mês/Sacola'),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='material',
            name='n_oficio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Ofício'),
        ),
        migrations.AlterField(
            model_name='material',
            name='peso_estimado',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso Est. (g)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Conferência'), ('NO_COFRE', 'No Cofre'), ('PRONTO_QUEIMA', 'Autorizado p/ Queima'), ('INCINERADO', 'Incinerado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='vara',
            field=models.CharField(choices=[('1ª VARA', '1ª Vara Criminal'), ('2ª VARA', '2ª Vara Criminal'), ('3ª VARA', '3ª Vara Criminal')], default='1ª VARA', max_length=20, verbose_name='Vara'),
        ),
    ]
