# Generated by Django 5.0.5 on 2026-02-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_material_posicao_sacola'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='policial_rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG do Policial'),
        ),
    ]
