# Generated by Django 6.0.3 on 2026-04-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_material_nome_popular_material_uso_pessoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipePM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('graduacao', models.CharField(choices=[('SD', 'Soldado'), ('CB', 'Cabo'), ('3SGT', '3º Sargento'), ('2SGT', '2º Sargento'), ('1SGT', '1º Sargento'), ('SUB', 'Subtenente'), ('2TEN', '2º Tenente'), ('1TEN', '1º Tenente'), ('CAP', 'Capitão'), ('MAJ', 'Major')], max_length=10)),
                ('rg', models.CharField(max_length=20)),
                ('unidade', models.CharField(choices=[('RPA', 'RPA'), ('DEAEV', 'DEAEV'), ('ROCAM', 'ROCAM'), ('GOTRAN', 'GOTRAN'), ('CAVALARIA', 'CAVALARIA'), ('CHOQUE', 'CHOQUE'), ('CHOQUE CANIL', 'CHOQUE CANIL'), ('TRANSITO', 'TRANSITO'), ('ROTAM', 'ROTAM'), ('CPU', 'CPU'), ('P2', 'P2'), ('OUTRA', 'Outra Unidade (Especificar)')], default='RPA', max_length=20)),
            ],
            options={
                'verbose_name': 'Equipe PM',
                'verbose_name_plural': 'Equipes PM',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NaturezaPenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('TC', 'Termo Circunstanciado'), ('IP', 'Inquérito Policial')], max_length=20)),
            ],
            options={
                'verbose_name': 'Natureza Penal',
                'verbose_name_plural': 'Naturezas Penais',
                'ordering': ['nome'],
            },
        ),
    ]
