# Generated by Django 5.0.5 on 2026-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_material_data_incineracao_material_data_oficio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='caixa',
        ),
        migrations.AddField(
            model_name='material',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote/Sacola (Ex: MAIO-2024)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='data_incineracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='vara',
            field=models.CharField(default='1ª VARA', max_length=20, verbose_name='Vara'),
        ),
    ]
