# Generated by Django 6.0.3 on 2026-04-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_add_natureza_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiado',
            name='depositario_fiel',
            field=models.BooleanField(default=False, verbose_name='Depositário Fiel'),
        ),
        migrations.AddField(
            model_name='noticiado',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='material',
            name='substancia',
            field=models.CharField(blank=True, choices=[('MACONHA', 'Maconha (Flor/Cume)'), ('SKUNK', 'Skunk (Maconha Importada)'), ('HASHISH', 'Haxixe (Hashish)'), ('COCAINA_PO', 'Cocaína (Pó/Branca)'), ('COCAINA_CRA', 'Crack (Cocaína Base)'), ('OPIACEOS', 'Ópio / Heroína'), ('MDF', 'Maconha de Fumo (MDF)'), ('LSD', 'LSD (Ácido)'), ('ECSTASY', 'Ecstasy / MDMA'), ('METANFETAMINA', 'Metanfetamina (Crystal)'), ('COCAINAMINA', 'Cocainaína (Merla)'), ('RECEPTACULO', 'Receptáculo/Eppendorf'), ('SEMENTE', 'Semente de Maconha'), ('COLHEITA', 'Planta/Colheita de Maconha'), ('OUTRA', 'Outra Substância')], max_length=50, null=True),
        ),
    ]
