# Generated by Django 5.0.5 on 2026-03-19 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_material_autorizado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='data_conferencia_judicial',
            new_name='data_autorizacao',
        ),
        migrations.RemoveField(
            model_name='material',
            name='observacao_autorizacao',
        ),
        migrations.AlterField(
            model_name='material',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_feitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
