# Generated by Django 5.0.5 on 2026-02-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_ocorrencia_policial_rg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='policial_rg',
            new_name='rg_policial',
        ),
    ]
