# Generated by Django 5.0.5 on 2026-02-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_remove_material_caixa_material_lote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material Custodiado', 'verbose_name_plural': 'Materiais Custodiados'},
        ),
        migrations.AddField(
            model_name='material',
            name='unidade',
            field=models.CharField(choices=[('G', 'Gramas (g)'), ('U', 'Unidades (un)'), ('P', 'Pés (un)')], default='G', max_length=1, verbose_name='Medida'),
        ),
        migrations.AlterField(
            model_name='material',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote/Sacola'),
        ),
        migrations.AlterField(
            model_name='material',
            name='peso_estimado',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Qtd/Peso Est.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='peso_real',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Qtd/Peso Real'),
        ),
    ]
