# Generated by Django 6.0.3 on 2026-04-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_add_observacao_depositario'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='eprotocolo_geral',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Ofício/EProtocolo'),
        ),
    ]
