# Generated by Django 6.0.3 on 2026-04-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_add_eprotocolo_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='numero_lacre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Lacre (Cadeia de Custódia)'),
        ),
    ]
