# Generated by Django 5.0.5 on 2026-02-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_material_options_material_unidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
        migrations.RemoveField(
            model_name='material',
            name='data_oficio',
        ),
        migrations.AddField(
            model_name='material',
            name='caixa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='bou',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nº Ocorrência'),
        ),
        migrations.AlterField(
            model_name='material',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='n_oficio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='noticiado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='peso_estimado',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='peso_real',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='substancia',
            field=models.CharField(choices=[('MACONHA', 'Maconha'), ('COCAINA', 'Cocaína'), ('CRACK', 'Crack'), ('PE_MACONHA', 'Pé de Maconha'), ('SINTETICA', 'Droga Sintética')], max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade',
            field=models.CharField(choices=[('G', 'Gramas (g)'), ('U', 'Unidades (un)')], default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='material',
            name='vara',
            field=models.CharField(max_length=100),
        ),
    ]
