# Generated by Django 6.0.3 on 2026-04-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_alter_material_numero_lacre'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='observacao_material',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Item'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Conferência / Erros BOU'),
        ),
    ]
