# Generated by Django 5.0.5 on 2026-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_material_conferido_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_CONFERENCIA', 'Aguardando Conferência'), ('NO_COFRE', 'No Cofre'), ('AUTORIZADO', 'Autorizado para Queima'), ('INCINERADO', 'Incinerado')], default='AGUARDANDO_CONFERENCIA', max_length=30),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='unidade_origem',
            field=models.CharField(choices=[('1CIA', '1ª CIA'), ('ROCAM', 'ROCAM'), ('CAVALARIA', 'CAVALARIA'), ('P2', 'P2'), ('GOTRAN', 'GOTRAN'), ('CHOQUE', 'CHOQUE'), ('OUTRA', 'Outra Unidade (Especificar)')], default='1CIA', max_length=20),
        ),
    ]
