# Generated by Django 5.0.5 on 2026-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_material_data_conferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='numero_vestigio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº do Vestígio (Lacre)'),
        ),
        migrations.AddField(
            model_name='material',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição/Obs'),
        ),
        migrations.AddField(
            model_name='material',
            name='policial_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Policial que Entregou'),
        ),
        migrations.AddField(
            model_name='material',
            name='processo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Processo'),
        ),
    ]
