# Generated by Django 6.0.3 on 2026-04-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_material_observacao_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteincineracao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.CharField(choices=[('ENTORPECENTE', 'Entorpecente'), ('SOM', 'Equipamento de Som (Perturbação)'), ('FACA', 'Arma Branca / Faca'), ('SIMULACRO', 'Simulacro / Arma de Fogo'), ('OUTROS', 'Outros Objetos (Gerais)'), ('DINHEIRO', 'Dinheiro / Valores monetários')], db_index=True, default='ENTORPECENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='numero_lacre',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Nº Lacre (Cadeia de Custódia)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Entrada no Cartório (Lacre Conferido)'), ('CONSTATAÇÃO', 'Processamento (Auto de Constatação Realizado)'), ('ARMAZENADO', 'Armazenamento (No Cofre)'), ('RETIRADO_PERICIA', 'Saída Temporária (Enviado para Perícia Externa)'), ('RETORNO_PERICIA', 'Retorno de Perícia (Re-armazenado)'), ('AUTORIZADO', 'Aguardando Incineração (Ordem Judicial)'), ('TRANSPORTE', 'Em Transporte (Para Destruição)'), ('INCINERADO', 'Fim de Custódia (Incinerado)'), ('AGUARDANDO_OFICIO', 'Aguardando Geração de Ofício (Materiais Gerais)'), ('OFICIO_GERADO', 'Ofício Gerado (Aguardando Transporte)'), ('EM_TRANSPORTE_FORUM', 'Em Transporte (Para o Fórum)'), ('ENTREGUE_AO_JUDICIARIO', 'Entregue ao Judiciário (Fórum / Recibo Anexado)'), ('AGUARDANDO_GUIA', 'Aguardando Guia de Depósito (Dinheiro)'), ('GUIA_GERADA', 'Guia Gerada (Aguardando Depósito)'), ('DEPOSITADO_JUDICIALMENTE', 'Depositado (Comprovante Anexado)')], db_index=True, default='RECEBIDO', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='substancia',
            field=models.CharField(blank=True, choices=[('MACONHA', 'Maconha (Flor/Cume)'), ('SKUNK', 'Skunk (Maconha Importada)'), ('HASHISH', 'Haxixe (Hashish)'), ('COCAINA_PO', 'Cocaína (Pó/Branca)'), ('COCAINA_CRA', 'Crack (Cocaína Base)'), ('OPIACEOS', 'Ópio / Heroína'), ('MDF', 'Maconha de Fumo (MDF)'), ('LSD', 'LSD (Ácido)'), ('ECSTASY', 'Ecstasy / MDMA'), ('METANFETAMINA', 'Metanfetamina (Crystal)'), ('COCAINAMINA', 'Cocainaína (Merla)'), ('RECEPTACULO', 'Receptáculo/Eppendorf'), ('SEMENTE', 'Semente de Maconha'), ('COLHEITA', 'Planta/Colheita de Maconha'), ('OUTRA', 'Outra Substância')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noticiado',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='noticiado',
            name='depositario_fiel',
            field=models.BooleanField(blank=True, default=False, verbose_name='Depositário Fiel'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_registro_bou',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data do Fato (BOU)'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='natureza_penal',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Tipos Penais / Natureza'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='vara',
            field=models.CharField(choices=[('VARA_01', '1ª Vara Criminal'), ('VARA_02', '2ª Vara Criminal'), ('VARA_03', '3ª Vara Criminal')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
