# Generated by Django 6.0.3 on 2026-04-14 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_alter_loteincineracao_data_criacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaIncineracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Código da Caixa')),
                ('data_incineracao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberta'), ('INCINERADO', 'Incinerada')], default='ABERTO', max_length=20)),
                ('eprotocolo_geral', models.CharField(blank=True, max_length=50, null=True, verbose_name='eProtocolo do Comando')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caixa de Incineração',
                'verbose_name_plural': 'Caixas de Incineração',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='loteincineracao',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='gestao.caixaincineracao'),
        ),
    ]
