# Generated by Django 5.0.5 on 2026-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_alter_ocorrencia_unidade_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='unidade_origem',
            field=models.CharField(choices=[('RPA', 'RPA'), ('DEAEV', 'DEAEV'), ('ROCAM', 'ROCAM'), ('GOTRAN', 'GOTRAN'), ('CAVALARIA', 'CAVALARIA'), ('CHOQUE', 'CHOQUE'), ('CHOQUE CANIL', 'CHOQUE CANIL'), ('TRANSITO', 'TRANSITO'), ('ROTAM', 'ROTAM'), ('CPU', 'CPU'), ('P2', 'P2'), ('OUTRA', 'Outra Unidade (Especificar)')], default='RPA', max_length=20),
        ),
    ]
