# Generated by Django 5.0.5 on 2026-03-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_ocorrencia_unidade_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='vara',
            field=models.CharField(choices=[('VARA_01', '1ª Vara Criminal'), ('VARA_02', '2ª Vara Criminal'), ('VARA_03', '3ª Vara Criminal')], max_length=20),
        ),
    ]
