# Generated by Django 6.0.3 on 2026-04-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_caixaincineracao_loteincineracao_caixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrogaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Substância')),
                ('permite_peso', models.BooleanField(default=True, verbose_name='Aceita Peso (g/kg)')),
                ('permite_unidade', models.BooleanField(default=False, verbose_name='Aceita Unidades (Pés/Comprimidos)')),
            ],
            options={
                'verbose_name': 'Configuração de Substância',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='batalhao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batalhão/OM'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='companhia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Companhia/Pelotão/Equipe'),
        ),
        migrations.AlterField(
            model_name='material',
            name='substancia',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='policial_graduacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='unidade_origem',
            field=models.CharField(default='RPA', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='vara',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
