# Generated by Django 5.0.5 on 2026-03-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_alter_ocorrencia_vara'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='autorizacao_judicial',
        ),
        migrations.RemoveField(
            model_name='material',
            name='autorizado_por',
        ),
        migrations.RemoveField(
            model_name='material',
            name='data_autorizacao',
        ),
        migrations.RemoveField(
            model_name='material',
            name='data_incineracao',
        ),
        migrations.RemoveField(
            model_name='material',
            name='eprotocolo_comando',
        ),
        migrations.RemoveField(
            model_name='material',
            name='n_oficio',
        ),
        migrations.AlterField(
            model_name='material',
            name='peso_estimado',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Peso Estimado'),
        ),
        migrations.AlterField(
            model_name='material',
            name='peso_real',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Peso Real'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade',
            field=models.CharField(choices=[('G', 'Gramas (g)'), ('KG', 'Quilos (kg)'), ('UN', 'Unidades (Pés/Comprimidos)')], default='G', max_length=3),
        ),
    ]
