# Generated by Django 6.0.3 on 2026-04-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_drogaconfig_ocorrencia_batalhao_ocorrencia_companhia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='substancia',
            field=models.CharField(blank=True, choices=[('MACONHA', 'Maconha (Flor/Cume)'), ('SKUNK', 'Skunk (Maconha Importada)'), ('HASHISH', 'Haxixe (Hashish)'), ('COCAINA_PO', 'Cocaína (Pó/Branca)'), ('COCAINA_CRA', 'Crack (Cocaína Base)'), ('OPIACEOS', 'Ópio / Heroína'), ('MDF', 'Maconha de Fumo (MDF)'), ('LSD', 'LSD (Ácido)'), ('ECSTASY', 'Ecstasy / MDMA'), ('METANFETAMINA', 'Metanfetamina (Crystal)'), ('COCAINAMINA', 'Cocainaína (Merla)'), ('RECEPTACULO', 'Receptáculo/Eppendorf'), ('SEMENTE', 'Semente de Maconha'), ('COLHEITA', 'Planta/Colheita de Maconha'), ('OUTRA', 'Outra Substância')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='vara',
            field=models.CharField(choices=[('VARA_01', '1ª Vara Criminal'), ('VARA_02', '2ª Vara Criminal'), ('VARA_03', '3ª Vara Criminal')], db_index=True, max_length=20),
        ),
    ]
